//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public enum Role
    {
        Intern,
        Manager,
        TeamLead,
        Tax_Intern,
        Tax_Technology_Intern

    }
    public partial class EmpDetail
    {
        public int Emp_id { get; set; }
       
        public string Fname { get; set; }
        public string Lname { get; set; }
        
        public Nullable<System.DateTime> DOB { get; set; }
        
        public string ContactNo { get; set; }
        
        public string Email_id { get; set; }
        
        public string PAN { get; set; }
        
        public string Address { get; set; }
        
        public string Password { get; set; }
        
        public string Designation { get; set; }
       
        public string Salary { get; set; }

        
    }
}
